version: '2.4'

services:

  sql:
    image: ${REGISTRY}demo/lighthouse-mssql:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    isolation: default
    build:
      context: ./images/windows/demo-mssql
      dockerfile: Dockerfile.linux
      args:
        BASE_IMAGE: ${REGISTRY}community/sitecore-xp0-custom-mssql:${SITECORE_VERSION}-linux
        SPE_ASSETS: ${REGISTRY}community/modules/custom-spe-assets:6.2-linux
        SXA_ASSETS: ${REGISTRY}community/modules/custom-sxa-xp1-assets:${SITECORE_VERSION}-linux
        HEADLESS_ASSETS: ${REGISTRY}community/modules/custom-sitecore-headless-services-xp1-assets:16.0.0-linux
        DEF_ASSETS: ${REGISTRY}community/modules/custom-def-xp0-assets:6.0.0-linux
        SFCRM_ASSETS: ${REGISTRY}community/modules/custom-sfcrm-xp0-assets:6.0.0-linux
        SFMCBDE_ASSETS: ${REGISTRY}community/modules/custom-sfmcbde-xp0-assets:6.0.0-linux
        SFMCCE_ASSETS: ${REGISTRY}community/modules/custom-sfmcce-xp0-assets:6.0.0-linux
        CMP_ASSETS: ${REGISTRY}community/modules/custom-cmp-xp1-assets:4.0.0-linux
        HORIZON_INTEGRATION_ASSETS: ${REGISTRY}community/modules/custom-horizon-integration-xp1-assets:2.25-linux
        XGEN_ASSETS:  ${REGISTRY}community/modules/custom-xgenerator-assets:${SITECORE_VERSION}-linux
        SITECORE_AI_ASSETS: ${REGISTRY}community/modules/custom-sitecore-ai-assets:${SITECORE_VERSION}-linux
        SITECORE_AI_DASHBOARD_ASSETS: ${REGISTRY}community/modules/custom-sitecore-ai-dashboard-assets:${SITECORE_VERSION}-linux
    volumes:
      - .\data\sql:/var/opt/mssql/data
    mem_limit: 2GB
    ports:
      - "44010:1433"
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      USER_PASSWORD: "b"
      ADMIN_PASSWORD: "b"
      ADMIN_USER_NAME: "sitecore\\superuser"
      DISABLE_DEFAULT_ADMIN: 'FALSE'
      EXM_BASE_URL: "http://${HOSTNAME_SUFFIX}"
      BOOT_OVERRIDE_SCRIPTS: "Demo-Boot-Platform-Linux.ps1"
      COVEO_ADMIN_USER_NAME: ${COVEO_ADMIN_USER_NAME}
  init:
    healthcheck:
      test: ["CMD", "powershell", "ps"]
    image: ${REGISTRY}demo/lighthouse-init:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    build:
      context: ./images/windows/demo-init
      dockerfile: Dockerfile.linux
      args:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/sdk:3.1-alpine
        BASE_IMAGE: mcr.microsoft.com/dotnet/runtime:3.1-alpine
    environment:
      ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
      ADMIN_USER_NAME: "superuser"
      HOST_CD: "http://cd"
      HOST_CM: "http://cm"
      HOST_PS: "http://ps:5000"
      HOST_ID: "http://id"
      MARKETING_DEFINITIONS_APIKEY: ${MARKETING_DEFINITIONS_APIKEY}
      COVEO_ORGANIZATION_ID: ${COVEO_ORGANIZATION_ID}
      COVEO_API_KEY: ${COVEO_API_KEY}
      COVEO_SEARCH_API_KEY: ${COVEO_SEARCH_API_KEY}
      COVEO_FARM_NAME: ${COVEO_FARM_NAME}
      COVEO_ADMIN_USER_NAME: ${COVEO_ADMIN_USER_NAME}